### ISSUE TITLE
error ...rest in render

### ISSUE THREAD

**Issue by fbacker** [nrako/react-component-resizable#27] opened 2016-09-30 14:20 UTC
ERROR in ./~/react-component-resizable/src/component.js
	Module parse failed: /Volumes/Work/react-native/BingoLotto/node_modules/react-component-resizable/src/component.js Unexpected token (87:74)
	You may need an appropriate loader to handle this file type.
	SyntaxError: Unexpected token (87:74)
	    at Parser.pp$4.raise (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
	    at Parser.pp.unexpected (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
	    at Parser.pp$3.parseIdent (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:2189:12)
	    at Parser.pp$3.parsePropertyName (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:2052:101)
	    at Parser.pp$3.parseObj (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:1988:14)
	    at Parser.pp$2.parseBindingAtom (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:1414:19)
	    at Parser.pp$1.parseVarId (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:1049:20)
	    at Parser.pp$1.parseVar (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:1032:14)
	    at Parser.pp$1.parseVarStatement (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:917:10)
	    at Parser.pp$1.parseStatement (/Volumes/Work/react-native/BingoLotto/node_modules/webpack/node_modules/acorn/dist/acorn.js:706:19)
	 @ ./~/react-component-resizable/index.js 1:17-43

Error at

    const {triggersClass, expandClass, contractClass, embedCss, onResize, ...rest} = this.props;
    var props = objectAssign({}, rest, {onScroll: this.onScroll, ref: 'resizable'});

Change to

    const {triggersClass, expandClass, contractClass, embedCss, onResize} = this.props;
    var props = objectAssign({}, {onScroll: this.onScroll, ref: 'resizable'});

**Comment by nrako** [comment] 2016-10-16 19:38
Hi @fbacker, thanks for reporting this. I believe this is actually a duplicate of #24, which should be fixed in `1.1.0-rc1`. See my comment https://github.com/nrako/react-component-resizable/issues/24#issuecomment-254068932

**Closed by nrako** 2016-10-16 19:38 UTC
